### PR TITLE
Fedora 26 build support

### PR DESCRIPTION
**Pull request by fepitre**
Add Fedora 26 template build support

### CODE REVIEW

**Comment by marmarek** [comment]
I'm in the process of building fc26 packages for all the components. Some r3.2 are already there, but not all. After that I'll trigger travis to retry...
Is anything else I need to merge before? https://github.com/QubesOS/qubes-linux-utils/pull/18 ?

**Comment by marmarek** [comment]
Ough, It looks like something have changed in Travis-CI environment, non-minimal template builds fails with "No space left on device"

**Comment by fepitre** [comment]
Yes I saw it earlier the problem of disk space. Indeed, you need the fix for linux-utils because I forgot to pull a request with others GCC fixes last time. Today I checked all my updates and I normally have pushed everything for FC26 template. Tomorrow, I will update all my repos with respect to the QubesOS upstream and rebuild everything for r3.2 and r4.0 to double check again. I'm trying to implement a simple automatic workflow on my servers to easily keep updated and move between QubesOS repositories -> My forks of them -> my devel branches and vice versa.

**Comment by marmarek** [comment]
I recommend https://www.qubes-os.org/doc/development-workflow/ (especially the part about local yum repo) and https://github.com/marmarek/qubes-builder/blob/master/doc/Configuration.md#increment_devel_versions
Also, qubes-builder have `make prepare-merge`, `make do-merge` and `make show-vtags` (also shows current branch) which are quite useful too.

**Comment by marmarek** [comment]
I've optimized disk usage of template builder, built all packages for fc26 for both r3.2 and r4.0 and now Travis-CI reports successful template build!

**Comment by fepitre** [comment]
Great. One question, do you have Travis-CI hosted in your infrastructure?

**Comment by marmarek** [comment]
No, we're using free travis-ci.org service.

**Pull request merged**
