### PR TITLE
Update XFCE

### PR DESCRIPTION
**Pull request by fepitre**

### CODE REVIEW

**Comment by fepitre** [comment]
As you suggested, I push directly to let Travis do the test. I'm currently building a 'release3.3' so my infra is already busy.

'Release3.3': release 3.2 with FC25 as dom0, FC26 and Stretch as templates. It is done with some adjustments: xen-4.6.6 with a gmp patch (maybe related to the fact that i'm building in it using a KVM VM), core-libvirt v3.1.0 (due to python version), and just a backport of one of your commit in mgmt-salt (about /etc/minion.d). But, I'm encountering a Grub bug when installing in an R3.2 HVM. Installation works fine but after the first reboot, I'm booting directly to a grub console without nothing (using the master branch of the installer). So I will test on a physical machine directly (maybe a bug related to /dev/sda <> /dev/xvda ? strange because R4.0 install fines in R3.2 HVM).

**Comment by fepitre** [comment]
Ok, the builds failed because qubes-core-agent-thunar and qubes-gui-agent-xfce are not yet available in the repos.

**Comment by marmarek** [comment]
This package isn't available in 3.2 at all, only 4.0. Not sure if worth backporting, but if you want, feel free.

**Comment by fepitre** [comment]
Ok. I will check later. Otherwise, my other problem is probably due to the fact I used kernel-4.14 where package is named "kernel-latest"....

**Pull request merged**
