### PR TITLE
Utils

### PR DESCRIPTION
**Pull request by fepitre**
Add some useful tools (related discussion: https://github.com/QubesOS/qubes-builder-fedora/pull/17)

### CODE REVIEW

**Comment by fepitre** [comment]
Travis said: all the tests are 👍

**Comment by marmarek** [comment]
I totally forgot I've added template size listing at the end of build in travis, so we can use this to check the sizes for all the configurations. For fc26 on 4.0 it says ~1.5GB...

**Comment by fepitre** [comment]
This is strange. Will do a clean build again to check if this is not due to not proper cleaned img in prepared templates.

**Comment by fepitre** [comment]
This is strange. Here is what I have done:

    cleaned everything, used the latest version of the master conf,
    added USE_QUBES_REPO_VERSION=4.0, USE_QUBES_REPO_TESTING=1

With the default TEMPLATE_ROOT_WITH_PARTITIONS = 1, the template size is 1263974972 qubes-template-fedora-26-4.0.0-201802172224.noarch.rpm and with TEMPLATE_ROOT_WITH_PARTITIONS = 0, the template size is 1149483024 qubes-template-fedora-26-4.0.0-201802180748.noarch.rpm

I don't understand why I have smaller images. I will investigate.

**Comment by marmarek** [comment]
Note that build in travis use online repositories exclusively. I.e. COMPONENTS contains only related builder plugins and template builder itself. This may affect what versions of some packages are used.

**Comment by marmarek** [comment]
You can download complete build log from travis, and compare list of packages (those 2-3 dnf install calls summary).

**Comment by marmarek** [comment]
Have you found the difference? Maybe you could upload a log of your build so I could compare it?

**Comment by fepitre** [comment]
I had not the time to do it yet. I can upload the log tomorrow.

**Comment by fepitre** [comment]
@marmarek : here is the log https://gist.github.com/fepitre/a40ba7ad32dc66d467b563acd61c3788
I will more time this evening and I will adjust the PR for Xen.

**Comment by marmarek** [comment]
Ok, I've compared the logs, and... have no idea. Installed packages are almost identical (there is slight difference in base packages, but looks like your build should be even larger because of `glibc-all-langpacks` vs `glibc-langpack-zu`).
One major difference is that travis build have `TEMPLATE_ROOT_WITH_PARTITIONS=1`, which results in kernel + grub installation, but that not explain such big difference. According to log, those packages are ~170MB. And the difference in raw `root.img` file is 3586892 vs 4205788.

Maybe that's because quite old software in travis (including rpm), affecting some compression, filesystem layout etc? I'd try building it locally.

**Comment by marmarek** [comment]
Ok, local build with `TEMPLATE_ROOT_WITH_PARTITIONS=1`: 1.2GB (1265415862 bytes).
So, this is something wrong with Travis.

**Comment by fepitre** [comment]
I was about to redo the build again but good to know you have same results. So probably travis is caching things or like you said old software. The test to be done would be to run the build like travis do (in an Ubuntu environment?) etc. but...does it worth the try...

**Pull request merged**
